// Command pagegen emits a React page skeleton from a OneDev Wicket HTML file.
//
// Usage (from repo root):
//
//	go run ./buildx-server/cmd/pagegen \
//	  -html references/onedev/server-core/src/main/java/io/onedev/server/web/page/security/LoginPage.html \
//	  -page LoginPage \
//	  -out buildx-web/src/pages/security/LoginPage.tsx
//
// The output is a starting point for 1:1 porting — wire forms, API, and state by hand.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
)

var (
	wicketTag      = regexp.MustCompile(`</?wicket:[^>]*>`)
	wicketAttr     = regexp.MustCompile(`\s+wicket:[^=]*="[^"]*"`)
	wicketT        = regexp.MustCompile(`<wicket:t>([^<]*)</wicket:t>`)
	wicketSvg      = regexp.MustCompile(`<wicket:svg href="([^"]+)"([^/]*)/>`)
	tPlaceholder   = regexp.MustCompile(`\s+t:placeholder="([^"]+)"`)
	tValue         = regexp.MustCompile(`\s+t:value="([^"]+)"`)
	tTippy         = regexp.MustCompile(`\s+t:data-tippy-content="([^"]+)"`)
	selfCloseInput = regexp.MustCompile(`<input([^>]*)/>`)
)

func wicketToJsx(html string) string {
	s := html
	s = wicketTag.ReplaceAllString(s, "")
	s = wicketAttr.ReplaceAllString(s, "")
	s = wicketT.ReplaceAllString(s, "$1")
	s = wicketSvg.ReplaceAllString(s, `<img src="/~icon/$1.svg" alt="" class="icon"$2 />`)
	s = tPlaceholder.ReplaceAllString(s, ` placeholder="$1"`)
	s = tValue.ReplaceAllString(s, ` defaultValue="$1"`)
	s = tTippy.ReplaceAllString(s, ` title="$1"`)
	s = selfCloseInput.ReplaceAllString(s, `<input$1 />`)
	return strings.TrimSpace(s)
}

const componentTmpl = `// Code generated by pagegen from OneDev Wicket HTML — edit before merge.
// Reference: {{.RefPath}}
import { SimpleLayout } from "../../layout/SimpleLayout";
import { useSimplePage } from "../../hooks/useSimplePage";

export function {{.PageName}}() {
  useSimplePage("{{.PageName}}");

  return (
    <SimpleLayout title="{{.PageName}}" subTitle={null}>
{{.Body}}
    </SimpleLayout>
  );
}
`

func main() {
	htmlPath := flag.String("html", "", "path to OneDev *Page.html")
	pageName := flag.String("page", "", "React component name (e.g. LoginPage)")
	outPath := flag.String("out", "", "output .tsx path")
	flag.Parse()

	if *htmlPath == "" || *pageName == "" || *outPath == "" {
		flag.Usage()
		os.Exit(2)
	}

	raw, err := os.ReadFile(*htmlPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read html: %v\n", err)
		os.Exit(1)
	}

	body := wicketToJsx(string(raw))
	indented := indentJsx(body, 6)

	tmpl := template.Must(template.New("page").Parse(componentTmpl))
	var buf strings.Builder
	err = tmpl.Execute(&buf, map[string]string{
		"PageName": *pageName,
		"RefPath":  *htmlPath,
		"Body":     indented,
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "template: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*outPath, []byte(buf.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s\n", *outPath)
}

func indentJsx(s string, spaces int) string {
	pad := strings.Repeat(" ", spaces)
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		if strings.TrimSpace(line) != "" {
			lines[i] = pad + line
		}
	}
	return strings.Join(lines, "\n")
}
