import type { RouteDefinition } from "./types";

/** OneDev BaseUrlMapper global routes (paths starting with /~). */
export const GLOBAL_ROUTES: RouteDefinition[] = [
  { path: "/~init", page: "ServerInitPage", title: "Server Initialization", ref: "web/page/serverinit/ServerInitPage", layout: "simple", known: "serverInit" },
  { path: "/~login", page: "LoginPage", title: "Sign In", ref: "web/page/security/LoginPage", layout: "simple", known: "login" },
  { path: "/~logout", page: "LogoutPage", title: "Sign Out", ref: "web/page/security/LogoutPage", layout: "simple", known: "logout" },
  { path: "/~signup", page: "SignUpPage", title: "Sign Up", ref: "web/page/security/SignUpPage", layout: "simple", known: "signup" },
  { path: "/~reset-password/:passwordResetCode", page: "PasswordResetPage", title: "Reset Password", ref: "web/page/security/PasswordResetPage", layout: "simple", known: "passwordReset" },
  { path: "/~verify-email-address/:emailAddress/:verificationCode", page: "EmailAddressVerificationPage", title: "Verify Email", ref: "web/page/security/EmailAddressVerificationPage", layout: "simple", known: "emailVerification" },
  { path: "/~create-user-from-invitation/:emailAddress/:invitationCode", page: "CreateUserFromInvitationPage", title: "Create Account", ref: "web/page/security/CreateUserFromInvitationPage", layout: "simple", known: "createUserFromInvitation" },
  { path: "/~sso/:stage/:provider", page: "SsoProcessPage", title: "SSO", ref: "web/page/security/SsoProcessPage", layout: "simple", known: "ssoProcess" },
  { path: "/~oauth/callback", page: "OAuthCallbackPage", title: "OAuth", ref: "web/page/security/OAuthCallbackPage", layout: "simple", known: "oauthCallback" },

  { path: "/~projects", page: "ProjectListPage", title: "Projects", ref: "web/page/project/ProjectListPage", layout: "main", known: "projects" },
  { path: "/~projects/new", page: "NewProjectPage", title: "New Project", ref: "web/page/project/NewProjectPage", layout: "main", known: "newProject" },
  { path: "/~projects/import/:importer", page: "ProjectImportPage", title: "Import Project", ref: "web/page/project/imports/ProjectImportPage", layout: "main" },

  { path: "/~issues", page: "IssueListPage", title: "Issues", ref: "web/page/issues/IssueListPage", layout: "main", known: "issues" },
  { path: "/~pulls", page: "PullRequestListPage", title: "Pull Requests", ref: "web/page/pullrequests/PullRequestListPage", layout: "main", known: "pulls" },
  { path: "/~builds", page: "BuildListPage", title: "Builds", ref: "web/page/builds/BuildListPage", layout: "main", known: "builds" },
  { path: "/~packages", page: "PackListPage", title: "Packages", ref: "web/page/packs/PackListPage", layout: "main", known: "packages" },
  { path: "/~workspaces", page: "WorkspaceListPage", title: "Workspaces", ref: "web/page/workspaces/WorkspaceListPage", layout: "main", known: "workspaces" },

  { path: "/~my", page: "MyProfilePage", title: "My Profile", ref: "web/page/my/profile/MyProfilePage", layout: "main", known: "myProfile" },
  { path: "/~my/basic-setting", page: "MyBasicSettingPage", title: "Basic Settings", ref: "web/page/my/basicsetting/MyBasicSettingPage", layout: "main", known: "myBasicSetting" },
  { path: "/~my/email-addresses", page: "MyEmailAddressesPage", title: "Email Addresses", ref: "web/page/my/emailaddresses/MyEmailAddressesPage", layout: "main" },
  { path: "/~my/avatar", page: "MyAvatarPage", title: "Edit Avatar", ref: "web/page/my/avatar/MyAvatarPage", layout: "main", known: "myAvatar" },
  { path: "/~my/password", page: "MyPasswordPage", title: "Password", ref: "web/page/my/password/MyPasswordPage", layout: "main", known: "myPassword" },
  { path: "/~my/ai-model-setting", page: "MyModelSettingPage", title: "AI Model", ref: "web/page/my/aisetting/MyModelSettingPage", layout: "main" },
  { path: "/~my/ai-system-prompt", page: "MySystemPromptPage", title: "AI System Prompt", ref: "web/page/my/aisetting/MySystemPromptPage", layout: "main" },
  { path: "/~my/ai-entitlement-setting", page: "MyEntitlementSettingPage", title: "AI Entitlement", ref: "web/page/my/aisetting/MyEntitlementSettingPage", layout: "main" },
  { path: "/~my/ssh-keys", page: "MySshKeysPage", title: "SSH Keys", ref: "web/page/my/sshkeys/MySshKeysPage", layout: "main", known: "mySshKeys" },
  { path: "/~my/gpg-keys", page: "MyGpgKeysPage", title: "GPG Keys", ref: "web/page/my/gpgkeys/MyGpgKeysPage", layout: "main" },
  { path: "/~my/access-tokens", page: "MyAccessTokensPage", title: "Access Tokens", ref: "web/page/my/accesstoken/MyAccessTokensPage", layout: "main", known: "myAccessTokens" },
  { path: "/~my/two-factor-authentication", page: "MyTwoFactorAuthenticationPage", title: "Two-factor Authentication", ref: "web/page/my/twofactorauthentication/MyTwoFactorAuthenticationPage", layout: "main" },
  { path: "/~my/sso-accounts", page: "MySsoAccountsPage", title: "SSO Accounts", ref: "web/page/my/ssoaccounts/MySsoAccountsPage", layout: "main" },
  { path: "/~my/query-watches/:tab", page: "MyQueryWatchesPage", title: "Query Watches", ref: "web/page/my/querywatch/MyQueryWatchesPage", layout: "main" },
  { path: "/~my/workspace-data", page: "MyWorkspaceDataPage", title: "Workspace Data", ref: "web/page/my/workspacedata/MyWorkspaceDataPage", layout: "main" },

  { path: "/~users/:user", page: "UserProfilePage", title: "User Profile", ref: "web/page/user/profile/UserProfilePage", layout: "main" },
  { path: "/~users/:user/basic-setting", page: "UserBasicSettingPage", title: "Basic Settings", ref: "web/page/user/basicsetting/UserBasicSettingPage", layout: "main" },
  { path: "/~users/:user/email-setting", page: "UserEmailAddressesPage", title: "Email Addresses", ref: "web/page/user/emailaddresses/UserEmailAddressesPage", layout: "main" },
  { path: "/~users/:user/groups", page: "UserMembershipsPage", title: "Groups", ref: "web/page/user/membership/UserMembershipsPage", layout: "main" },
  { path: "/~users/:user/authorizations", page: "UserAuthorizationsPage", title: "Authorizations", ref: "web/page/user/authorization/UserAuthorizationsPage", layout: "main", known: "userAuthorizations" },
  { path: "/~users/:user/avatar", page: "UserAvatarPage", title: "Edit Avatar", ref: "web/page/user/avatar/UserAvatarPage", layout: "main" },
  { path: "/~users/:user/password", page: "UserPasswordPage", title: "Password", ref: "web/page/user/password/UserPasswordPage", layout: "main" },
  { path: "/~users/:user/ai-model-setting", page: "UserModelSettingPage", title: "AI Model", ref: "web/page/user/aisetting/UserModelSettingPage", layout: "main" },
  { path: "/~users/:user/ai-system-prompt", page: "UserSystemPromptPage", title: "AI System Prompt", ref: "web/page/user/aisetting/UserSystemPromptPage", layout: "main" },
  { path: "/~users/:user/ai-entitlement-setting", page: "UserEntitlementSettingPage", title: "AI Entitlement", ref: "web/page/user/aisetting/UserEntitlementSettingPage", layout: "main" },
  { path: "/~users/:user/ssh-keys", page: "UserSshKeysPage", title: "SSH Keys", ref: "web/page/user/sshkeys/UserSshKeysPage", layout: "main" },
  { path: "/~users/:user/gpg-keys", page: "UserGpgKeysPage", title: "GPG Keys", ref: "web/page/user/gpgkeys/UserGpgKeysPage", layout: "main" },
  { path: "/~users/:user/access-tokens", page: "UserAccessTokensPage", title: "Access Tokens", ref: "web/page/user/accesstoken/UserAccessTokensPage", layout: "main" },
  { path: "/~users/:user/two-factor-authentication", page: "UserTwoFactorAuthenticationPage", title: "Two-factor Authentication", ref: "web/page/user/twofactorauthentication/UserTwoFactorAuthenticationPage", layout: "main" },
  { path: "/~users/:user/sso-accounts", page: "UserSsoAccountsPage", title: "SSO Accounts", ref: "web/page/user/ssoaccounts/UserSsoAccountsPage", layout: "main" },
  { path: "/~users/:user/query-watches/:tab", page: "UserQueryWatchesPage", title: "Query Watches", ref: "web/page/user/querywatch/UserQueryWatchesPage", layout: "main" },
  { path: "/~users/:user/workspace-data", page: "UserWorkspaceDataPage", title: "Workspace Data", ref: "web/page/user/workspacedata/UserWorkspaceDataPage", layout: "main" },

  { path: "/~administration/users", page: "UserListPage", title: "Users", ref: "web/page/admin/usermanagement/UserListPage", layout: "main", known: "userList" },
  { path: "/~administration/users/new", page: "NewUserPage", title: "New User", ref: "web/page/admin/usermanagement/NewUserPage", layout: "main", known: "newUser" },
  { path: "/~administration/invitations", page: "InvitationListPage", title: "Invitations", ref: "web/page/admin/usermanagement/InvitationListPage", layout: "main", known: "invitationList" },
  { path: "/~administration/invitations/new", page: "NewInvitationPage", title: "New Invitation", ref: "web/page/admin/usermanagement/NewInvitationPage", layout: "main", known: "newInvitation" },
  { path: "/~administration/roles", page: "RoleListPage", title: "Roles", ref: "web/page/admin/rolemanagement/RoleListPage", layout: "main", known: "roleList" },
  { path: "/~administration/roles/new", page: "NewRolePage", title: "New Role", ref: "web/page/admin/rolemanagement/NewRolePage", layout: "main" },
  { path: "/~administration/roles/:role", page: "RoleDetailPage", title: "Role", ref: "web/page/admin/rolemanagement/RoleDetailPage", layout: "main" },
  { path: "/~administration/groups", page: "GroupListPage", title: "Groups", ref: "web/page/admin/groupmanagement/GroupListPage", layout: "main", known: "groupList" },
  { path: "/~administration/groups/new", page: "NewGroupPage", title: "New Group", ref: "web/page/admin/groupmanagement/create/NewGroupPage", layout: "main" },
  { path: "/~administration/groups/:group", page: "GroupProfilePage", title: "Group", ref: "web/page/admin/groupmanagement/profile/GroupProfilePage", layout: "main" },
  { path: "/~administration/groups/:group/members", page: "GroupMembershipsPage", title: "Group Members", ref: "web/page/admin/groupmanagement/membership/GroupMembershipsPage", layout: "main" },
  { path: "/~administration/groups/:group/authorizations", page: "GroupAuthorizationsPage", title: "Group Authorizations", ref: "web/page/admin/groupmanagement/authorization/GroupAuthorizationsPage", layout: "main" },
  { path: "/~administration/labels", page: "LabelManagementPage", title: "Labels", ref: "web/page/admin/labelmanagement/LabelManagementPage", layout: "main" },
  { path: "/~administration/settings/system", page: "SystemSettingPage", title: "System Settings", ref: "web/page/admin/systemsetting/SystemSettingPage", layout: "main", known: "systemSetting" },
  { path: "/~administration/settings/security", page: "SecuritySettingPage", title: "Security Settings", ref: "web/page/admin/securitysetting/SecuritySettingPage", layout: "main", known: "securitySetting" },
  { path: "/~administration/settings/branding", page: "BrandingSettingPage", title: "Branding", ref: "web/page/admin/brandingsetting/BrandingSettingPage", layout: "main", known: "branding" },
  { path: "/~administration/settings/mail-service", page: "MailConnectorPage", title: "Mail Service", ref: "web/page/admin/mailservice/MailConnectorPage", layout: "main", known: "mailService" },
  { path: "/~administration/settings/service-desk-setting", page: "ServiceDeskSettingPage", title: "Service Desk", ref: "web/page/admin/servicedesk/ServiceDeskSettingPage", layout: "main" },
  { path: "/~administration/settings/authenticator", page: "AuthenticatorPage", title: "Authenticator", ref: "web/page/admin/authenticator/AuthenticatorPage", layout: "main" },
  { path: "/~administration/settings/sso-providers", page: "SsoProviderListPage", title: "SSO Providers", ref: "web/page/admin/ssosetting/SsoProviderListPage", layout: "main" },
  { path: "/~administration/settings/sso-providers/new", page: "NewSsoProviderPage", title: "New SSO Provider", ref: "web/page/admin/ssosetting/NewSsoProviderPage", layout: "main" },
  { path: "/~administration/settings/sso-providers/:provider", page: "SsoProviderDetailPage", title: "SSO Provider", ref: "web/page/admin/ssosetting/SsoProviderDetailPage", layout: "main" },
  { path: "/~administration/settings/ssh-server-key", page: "SshServerKeyPage", title: "SSH Server Key", ref: "web/page/admin/sshserverkey/SshServerKeyPage", layout: "main" },
  { path: "/~administration/settings/gpg-signing-key", page: "GpgSigningKeyPage", title: "GPG Signing Key", ref: "web/page/admin/gpgsigningkey/GpgSigningKeyPage", layout: "main" },
  { path: "/~administration/settings/gpg-trusted-keys", page: "GpgTrustedKeysPage", title: "GPG Trusted Keys", ref: "web/page/admin/gpgtrustedkeys/GpgTrustedKeysPage", layout: "main" },
  { path: "/~administration/settings/backup", page: "DatabaseBackupPage", title: "Database Backup", ref: "web/page/admin/databasebackup/DatabaseBackupPage", layout: "main" },
  { path: "/~administration/settings/alert", page: "AlertSettingPage", title: "Alerts", ref: "web/page/admin/alertsettings/AlertSettingPage", layout: "main" },
  { path: "/~administration/settings/performance", page: "PerformanceSettingPage", title: "Performance", ref: "web/page/admin/performancesetting/PerformanceSettingPage", layout: "main" },
  { path: "/~administration/settings/lite-ai-model", page: "LiteModelPage", title: "Lite AI Model", ref: "web/page/admin/aisetting/LiteModelPage", layout: "main" },
  { path: "/~administration/settings/chat-preserve-days", page: "ChatPreserveDaysPage", title: "Chat Preserve Days", ref: "web/page/admin/aisetting/ChatPreserveDaysPage", layout: "main" },
  { path: "/~administration/settings/:pluginSetting", page: "ContributedAdministrationSettingPage", title: "Settings", ref: "web/page/admin/pluginsettings/ContributedAdministrationSettingPage", layout: "main" },
  { path: "/~administration/settings/email-templates/issue-notification", page: "IssueNotificationTemplatePage", title: "Issue Notification", ref: "web/page/admin/emailtemplates/IssueNotificationTemplatePage", layout: "main" },
  { path: "/~administration/settings/email-templates/pull-request-notification", page: "PullRequestNotificationTemplatePage", title: "Pull Request Notification", ref: "web/page/admin/emailtemplates/PullRequestNotificationTemplatePage", layout: "main" },
  { path: "/~administration/settings/email-templates/build-notification", page: "BuildNotificationTemplatePage", title: "Build Notification", ref: "web/page/admin/emailtemplates/BuildNotificationTemplatePage", layout: "main" },
  { path: "/~administration/settings/email-templates/pack-notification", page: "PackNotificationTemplatePage", title: "Pack Notification", ref: "web/page/admin/emailtemplates/PackNotificationTemplatePage", layout: "main" },
  { path: "/~administration/settings/email-templates/workspace-notification", page: "WorkspaceNotificationTemplatePage", title: "Workspace Notification", ref: "web/page/admin/emailtemplates/WorkspaceNotificationTemplatePage", layout: "main" },
  { path: "/~administration/settings/email-templates/commit-notification", page: "CommitNotificationTemplatePage", title: "Commit Notification", ref: "web/page/admin/emailtemplates/CommitNotificationTemplatePage", layout: "main" },
  { path: "/~administration/settings/email-templates/issue-notification-unsubscribed", page: "IssueNotificationUnsubscribedTemplatePage", title: "Issue Notification Unsubscribed", ref: "web/page/admin/emailtemplates/IssueNotificationUnsubscribedTemplatePage", layout: "main" },
  { path: "/~administration/settings/email-templates/pull-request-notification-unsubscribed", page: "PullRequestNotificationUnsubscribedTemplatePage", title: "Pull Request Notification Unsubscribed", ref: "web/page/admin/emailtemplates/PullRequestNotificationUnsubscribedTemplatePage", layout: "main" },
  { path: "/~administration/settings/email-templates/service-desk-issue-opened", page: "ServiceDeskIssueOpenedTemplatePage", title: "Service Desk Issue Opened", ref: "web/page/admin/emailtemplates/ServiceDeskIssueOpenedTemplatePage", layout: "main" },
  { path: "/~administration/settings/email-templates/service-desk-issue-open-failed", page: "ServiceDeskIssueOpenFailedTemplatePage", title: "Service Desk Issue Open Failed", ref: "web/page/admin/emailtemplates/ServiceDeskIssueOpenFailedTemplatePage", layout: "main" },
  { path: "/~administration/settings/email-templates/user-invitation", page: "UserInvitationTemplatePage", title: "User Invitation", ref: "web/page/admin/emailtemplates/UserInvitationTemplatePage", layout: "main" },
  { path: "/~administration/settings/email-templates/email-verification", page: "EmailVerificationTemplatePage", title: "Email Verification", ref: "web/page/admin/emailtemplates/EmailVerificationTemplatePage", layout: "main" },
  { path: "/~administration/settings/email-templates/password-reset", page: "PasswordResetTemplatePage", title: "Password Reset", ref: "web/page/admin/emailtemplates/PasswordResetTemplatePage", layout: "main" },
  { path: "/~administration/settings/email-templates/stopwatch-overdue", page: "StopwatchOverdueTemplatePage", title: "Stopwatch Overdue", ref: "web/page/admin/emailtemplates/StopwatchOverdueTemplatePage", layout: "main" },
  { path: "/~administration/settings/email-templates/alert", page: "AlertTemplatePage", title: "Alert", ref: "web/page/admin/emailtemplates/AlertTemplatePage", layout: "main" },
  { path: "/~administration/settings/issue-fields", page: "IssueFieldListPage", title: "Issue Fields", ref: "web/page/admin/issuesetting/fieldspec/IssueFieldListPage", layout: "main", known: "issueFieldList" },
  { path: "/~administration/settings/issue-states", page: "IssueStateListPage", title: "Issue States", ref: "web/page/admin/issuesetting/statespec/IssueStateListPage", layout: "main", known: "issueStateList" },
  { path: "/~administration/settings/state-transitions", page: "StateTransitionListPage", title: "State Transitions", ref: "web/page/admin/issuesetting/transitionspec/StateTransitionListPage", layout: "main" },
  { path: "/~administration/settings/issue-boards", page: "DefaultBoardListPage", title: "Issue Boards", ref: "web/page/admin/issuesetting/defaultboard/DefaultBoardListPage", layout: "main" },
  { path: "/~administration/settings/issue-links", page: "LinkSpecListPage", title: "Issue Links", ref: "web/page/admin/issuesetting/linkspec/LinkSpecListPage", layout: "main" },
  { path: "/~administration/settings/time-tracking", page: "TimeTrackingSettingPage", title: "Time Tracking", ref: "web/page/admin/issuesetting/timetracking/TimeTrackingSettingPage", layout: "main" },
  { path: "/~administration/settings/issue-templates", page: "IssueTemplateListPage", title: "Issue Templates", ref: "web/page/admin/issuesetting/issuetemplate/IssueTemplateListPage", layout: "main" },
  { path: "/~administration/settings/commit-message-fix", page: "CommitMessageFixSettingPage", title: "Commit Message Fix", ref: "web/page/admin/issuesetting/commitmessagefix/CommitMessageFixSettingPage", layout: "main" },
  { path: "/~administration/settings/external-issue-transformers", page: "ExternalIssueTransformersPage", title: "External Issue Transformers", ref: "web/page/admin/issuesetting/externalissuepattern/ExternalIssueTransformersPage", layout: "main" },
  { path: "/~administration/settings/check-issue-integrity", page: "CheckIssueIntegrityPage", title: "Check Issue Integrity", ref: "web/page/admin/issuesetting/integritycheck/CheckIssueIntegrityPage", layout: "main" },
  { path: "/~administration/agents", page: "AgentListPage", title: "Agents", ref: "web/page/admin/buildsetting/agent/AgentListPage", layout: "main", known: "agentList" },
  { path: "/~administration/agents/:agent", page: "AgentOverviewPage", title: "Agent", ref: "web/page/admin/buildsetting/agent/AgentOverviewPage", layout: "main", known: "agentOverview" },
  { path: "/~administration/agents/:agent/builds", page: "AgentBuildsPage", title: "Agent Builds", ref: "web/page/admin/buildsetting/agent/AgentBuildsPage", layout: "main", known: "agentBuilds" },
  { path: "/~administration/agents/:agent/workspaces", page: "AgentWorkspacesPage", title: "Agent Workspaces", ref: "web/page/admin/buildsetting/agent/AgentWorkspacesPage", layout: "main", known: "agentWorkspaces" },
  { path: "/~administration/agents/:agent/log", page: "AgentLogPage", title: "Agent Log", ref: "web/page/admin/buildsetting/agent/AgentLogPage", layout: "main", known: "agentLog" },
  { path: "/~administration/settings/job-executors", page: "JobExecutorsPage", title: "Job Executors", ref: "web/page/admin/buildsetting/jobexecutor/JobExecutorsPage", layout: "main", known: "jobExecutors" },
  { path: "/~administration/settings/workspace-provisioners", page: "WorkspaceProvisionersPage", title: "Workspace Provisioners", ref: "web/page/admin/workspaceprovisioner/WorkspaceProvisionersPage", layout: "main" },
  { path: "/~administration/settings/groovy-scripts", page: "GroovyScriptListPage", title: "Groovy Scripts", ref: "web/page/admin/groovyscript/GroovyScriptListPage", layout: "main" },
  { path: "/~administration/server-log/:server", page: "ServerLogPage", title: "Server Log", ref: "web/page/admin/serverlog/ServerLogPage", layout: "main" },
  { path: "/~administration/server-information/:server", page: "ServerInformationPage", title: "Server Information", ref: "web/page/admin/serverinformation/ServerInformationPage", layout: "main" },

  { path: "/~help/incompatibilities", page: "IncompatibilitiesPage", title: "Incompatibilities", ref: "web/page/help/IncompatibilitiesPage", layout: "main", known: "incompatibilities" },
  { path: "/~help/api", page: "ResourceListPage", title: "RESTful API", ref: "web/page/help/ResourceListPage", layout: "main", known: "resourceList" },
  { path: "/~help/api/:resource", page: "ResourceDetailPage", title: "API Resource", ref: "web/page/help/ResourceDetailPage", layout: "main", known: "resourceDetail" },
  { path: "/~help/api/:resource/:method", page: "MethodDetailPage", title: "API Method", ref: "web/page/help/MethodDetailPage", layout: "main" },
  { path: "/~errors/404", page: "PageNotFoundErrorPage", title: "Page Not Found", ref: "web/page/error/PageNotFoundErrorPage", layout: "simple", known: "notFound" },
  { path: "/~test", page: "TestPage", title: "Test", ref: "web/page/test/TestPage", layout: "main" },
];
