import type { ProjectRouteDefinition } from "./types";

/** Suffix after project path (`/{project}` or `/{project}/~...`). Longest match wins. */
export const PROJECT_ROUTE_SUFFIXES: ProjectRouteDefinition[] = [
  { suffix: "", page: "ProjectDashboardPage", title: "Dashboard", ref: "web/page/project/dashboard/ProjectDashboardPage", known: "dashboard" },

  { suffix: "/~files", page: "ProjectBlobPage", title: "Files", ref: "web/page/project/blob/ProjectBlobPage", known: "blob" },
  { suffix: "/~commits", page: "ProjectCommitsPage", title: "Commits", ref: "web/page/project/commits/ProjectCommitsPage", known: "commits" },
  { suffix: "/~commits/:commit", page: "CommitDetailPage", title: "Commit", ref: "web/page/project/commits/CommitDetailPage", known: "commitDetail" },
  { suffix: "/~compare", page: "RevisionComparePage", title: "Compare", ref: "web/page/project/compare/RevisionComparePage", known: "compare" },
  { suffix: "/~stats/code/contribs", page: "CodeContribsPage", title: "Code Contributors", ref: "web/page/project/stats/code/CodeContribsPage", known: "codeContribs" },
  { suffix: "/~stats/code/lines", page: "SourceLinesPage", title: "Source Lines", ref: "web/page/project/stats/code/SourceLinesPage", known: "sourceLines" },
  { suffix: "/~stats/buildmetric", page: "BuildMetricStatsPage", title: "Build Metrics", ref: "web/page/project/stats/buildmetric/BuildMetricStatsPage", known: "buildMetricStats" },
  { suffix: "/~branches", page: "ProjectBranchesPage", title: "Branches", ref: "web/page/project/branches/ProjectBranchesPage", known: "branches" },
  { suffix: "/~tags", page: "ProjectTagsPage", title: "Tags", ref: "web/page/project/tags/ProjectTagsPage", known: "tags" },
  { suffix: "/~code-comments", page: "ProjectCodeCommentsPage", title: "Code Comments", ref: "web/page/project/codecomments/ProjectCodeCommentsPage", known: "codeComments" },
  { suffix: "/~code-comments/:codeComment/invalid", page: "InvalidCodeCommentPage", title: "Invalid Code Comment", ref: "web/page/project/codecomments/InvalidCodeCommentPage" },

  { suffix: "/~pulls", page: "ProjectPullRequestsPage", title: "Pull Requests", ref: "web/page/project/pullrequests/ProjectPullRequestsPage", known: "prList" },
  { suffix: "/~pulls/new", page: "NewPullRequestPage", title: "New Pull Request", ref: "web/page/project/pullrequests/create/NewPullRequestPage", known: "newPullRequest" },
  { suffix: "/~pulls/:request", page: "PullRequestActivitiesPage", title: "Pull Request", ref: "web/page/project/pullrequests/detail/activities/PullRequestActivitiesPage", known: "prActivities" },
  { suffix: "/~pulls/:request/code-comments", page: "PullRequestCodeCommentsPage", title: "Pull Request Code Comments", ref: "web/page/project/pullrequests/detail/codecomments/PullRequestCodeCommentsPage", known: "prCodeComments" },
  { suffix: "/~pulls/:request/changes", page: "PullRequestChangesPage", title: "Pull Request Changes", ref: "web/page/project/pullrequests/detail/changes/PullRequestChangesPage", known: "prChanges" },
  { suffix: "/~pulls/:request/invalid", page: "InvalidPullRequestPage", title: "Invalid Pull Request", ref: "web/page/project/pullrequests/InvalidPullRequestPage", known: "prInvalid" },

  { suffix: "/~boards", page: "IssueBoardsPage", title: "Issue Boards", ref: "web/page/project/issues/boards/IssueBoardsPage", known: "boards" },
  { suffix: "/~boards/:board", page: "IssueBoardsPage", title: "Issue Board", ref: "web/page/project/issues/boards/IssueBoardsPage", known: "boards" },
  { suffix: "/~issues", page: "ProjectIssueListPage", title: "Issues", ref: "web/page/project/issues/list/ProjectIssueListPage", known: "issueList" },
  { suffix: "/~issues/new", page: "NewIssuePage", title: "New Issue", ref: "web/page/project/issues/create/NewIssuePage", known: "newIssue" },
  { suffix: "/~issues/import/:importer", page: "IssueImportPage", title: "Import Issues", ref: "web/page/project/issues/imports/IssueImportPage" },
  { suffix: "/~issues/:issue", page: "IssueDetailPage", title: "Issue", ref: "web/page/project/issues/detail/IssueDetailPage", known: "issueDetail" },
  { suffix: "/~issues/:issue/commits", page: "IssueCommitsPage", title: "Issue Commits", ref: "web/page/project/issues/detail/IssueCommitsPage", known: "issueCommits" },
  { suffix: "/~issues/:issue/pulls", page: "IssuePullRequestsPage", title: "Issue Pull Requests", ref: "web/page/project/issues/detail/IssuePullRequestsPage", known: "issuePulls" },
  { suffix: "/~issues/:issue/builds", page: "IssueBuildsPage", title: "Issue Builds", ref: "web/page/project/issues/detail/IssueBuildsPage", known: "issueBuilds" },
  { suffix: "/~issues/:issue/authorizations", page: "IssueAuthorizationsPage", title: "Issue Authorizations", ref: "web/page/project/issues/detail/IssueAuthorizationsPage" },
  { suffix: "/~iterations", page: "IterationListPage", title: "Iterations", ref: "web/page/project/issues/iteration/IterationListPage", known: "iterationList" },
  { suffix: "/~iterations/new", page: "NewIterationPage", title: "New Iteration", ref: "web/page/project/issues/iteration/NewIterationPage", known: "newIteration" },
  { suffix: "/~iterations/:iteration", page: "IterationIssuesPage", title: "Iteration", ref: "web/page/project/issues/iteration/IterationIssuesPage", known: "iterationDetail" },
  { suffix: "/~iterations/:iteration/burndown", page: "IterationBurndownPage", title: "Burndown", ref: "web/page/project/issues/iteration/IterationBurndownPage", known: "iterationBurndown" },
  { suffix: "/~iterations/:iteration/edit", page: "IterationEditPage", title: "Edit Iteration", ref: "web/page/project/issues/iteration/IterationEditPage", known: "iterationEdit" },

  { suffix: "/~builds", page: "ProjectBuildsPage", title: "Builds", ref: "web/page/project/builds/ProjectBuildsPage", known: "buildList" },
  { suffix: "/~builds/:build", page: "BuildDashboardPage", title: "Build", ref: "web/page/project/builds/detail/dashboard/BuildDashboardPage", known: "buildDashboard" },
  { suffix: "/~builds/:build/pipeline", page: "BuildPipelinePage", title: "Build Pipeline", ref: "web/page/project/builds/detail/pipeline/BuildPipelinePage", known: "buildPipeline" },
  { suffix: "/~builds/:build/log", page: "BuildLogPage", title: "Build Log", ref: "web/page/project/builds/detail/log/BuildLogPage", known: "buildLog" },
  { suffix: "/~builds/:build/changes", page: "BuildChangesPage", title: "Build Changes", ref: "web/page/project/builds/detail/changes/BuildChangesPage", known: "buildChanges" },
  { suffix: "/~builds/:build/fixed-issues", page: "FixedIssuesPage", title: "Fixed Issues", ref: "web/page/project/builds/detail/issues/FixedIssuesPage", known: "buildFixedIssues" },
  { suffix: "/~builds/:build/artifacts", page: "BuildArtifactsPage", title: "Build Artifacts", ref: "web/page/project/builds/detail/artifacts/BuildArtifactsPage", known: "buildArtifacts" },
  { suffix: "/~builds/:build/packages/:type", page: "BuildPacksPage", title: "Build Packages", ref: "web/page/project/builds/detail/pack/BuildPacksPage", known: "buildPacks" },
  { suffix: "/~builds/:build/invalid", page: "InvalidBuildPage", title: "Invalid Build", ref: "web/page/project/builds/detail/InvalidBuildPage" },
  { suffix: "/~builds/:build/reports/:report", page: "BuildReportPage", title: "Build Report", ref: "web/page/project/builds/detail/report/BuildReportPage", known: "buildReport" },

  { suffix: "/~packages", page: "ProjectPacksPage", title: "Packages", ref: "web/page/project/packs/ProjectPacksPage", known: "projectPacks" },
  { suffix: "/~packages/:pack", page: "PackDetailPage", title: "Package", ref: "web/page/project/packs/detail/PackDetailPage", known: "packDetail" },
  { suffix: "/~workspaces", page: "ProjectWorkspacesPage", title: "Workspaces", ref: "web/page/project/workspaces/ProjectWorkspacesPage", known: "projectWorkspaces" },
  { suffix: "/~workspaces/:workspace", page: "WorkspaceDashboardPage", title: "Workspace", ref: "web/page/project/workspaces/detail/dashboard/WorkspaceDashboardPage", known: "workspaceDashboard" },
  { suffix: "/~workspaces/:workspace/terminals/:shell", page: "WorkspaceTerminalPage", title: "Workspace Terminal", ref: "web/page/project/workspaces/detail/terminal/WorkspaceTerminalPage" },
  { suffix: "/~workspaces/:workspace/changes", page: "WorkspaceChangesPage", title: "Workspace Changes", ref: "web/page/project/workspaces/detail/changes/WorkspaceChangesPage", known: "workspaceChanges" },
  { suffix: "/~workspaces/:workspace/log", page: "WorkspaceLogPage", title: "Workspace Log", ref: "web/page/project/workspaces/detail/log/WorkspaceLogPage", known: "workspaceLog" },

  { suffix: "/~children", page: "ProjectChildrenPage", title: "Child Projects", ref: "web/page/project/children/ProjectChildrenPage", known: "children" },
  { suffix: "/~no-storage", page: "NoProjectStoragePage", title: "No Storage", ref: "web/page/project/NoProjectStoragePage" },

  { suffix: "/~settings/general", page: "GeneralProjectSettingPage", title: "General Settings", ref: "web/page/project/setting/general/GeneralProjectSettingPage" },
  { suffix: "/~settings/user-authorizations", page: "UserAuthorizationsPage", title: "User Authorizations", ref: "web/page/project/setting/authorization/UserAuthorizationsPage", known: "projectUserAuthorizations" },
  { suffix: "/~settings/group-authorizations", page: "GroupAuthorizationsPage", title: "Group Authorizations", ref: "web/page/project/setting/authorization/GroupAuthorizationsPage" },
  { suffix: "/~settings/avatar-edit", page: "AvatarEditPage", title: "Edit Avatar", ref: "web/page/project/setting/avatar/AvatarEditPage" },
  { suffix: "/~settings/branch-protection", page: "BranchProtectionsPage", title: "Branch Protection", ref: "web/page/project/setting/code/branchprotection/BranchProtectionsPage" },
  { suffix: "/~settings/tag-protection", page: "TagProtectionsPage", title: "Tag Protection", ref: "web/page/project/setting/code/tagprotection/TagProtectionsPage" },
  { suffix: "/~settings/code-analysis", page: "CodeAnalysisSettingPage", title: "Code Analysis", ref: "web/page/project/setting/code/analysis/CodeAnalysisSettingPage" },
  { suffix: "/~settings/git-pack-config", page: "GitPackConfigPage", title: "Git Pack Config", ref: "web/page/project/setting/code/git/GitPackConfigPage" },
  { suffix: "/~settings/pull-request", page: "PullRequestSettingPage", title: "Pull Request Settings", ref: "web/page/project/setting/code/pullrequest/PullRequestSettingPage", known: "pullRequestSetting" },
  { suffix: "/~settings/build/job-secrets", page: "JobSecretsPage", title: "Job Secrets", ref: "web/page/project/setting/build/JobSecretsPage" },
  { suffix: "/~settings/build/job-properties", page: "JobPropertiesPage", title: "Job Properties", ref: "web/page/project/setting/build/JobPropertiesPage" },
  { suffix: "/~settings/build/build-preserve-rules", page: "BuildPreservationsPage", title: "Build Preservations", ref: "web/page/project/setting/build/BuildPreservationsPage" },
  { suffix: "/~settings/build/default-fixed-issues-filter", page: "DefaultFixedIssueFiltersPage", title: "Default Fixed Issues Filter", ref: "web/page/project/setting/build/DefaultFixedIssueFiltersPage" },
  { suffix: "/~settings/build/cache-management", page: "CacheManagementPage", title: "Cache Management", ref: "web/page/project/setting/cache/CacheManagementPage" },
  { suffix: "/~settings/issue/state-transitions", page: "ProjectStateTransitionListPage", title: "State Transitions", ref: "web/page/project/setting/issuesetting/ProjectStateTransitionListPage" },
  { suffix: "/~settings/issue/branch-prefix", page: "IssueBranchPrefixPage", title: "Issue Branch Prefix", ref: "web/page/project/setting/issuesetting/IssueBranchPrefixPage" },
  { suffix: "/~settings/service-desk", page: "ServiceDeskSettingPage", title: "Service Desk", ref: "web/page/project/setting/servicedesk/ServiceDeskSettingPage" },
  { suffix: "/~settings/web-hooks", page: "WebHooksPage", title: "Web Hooks", ref: "web/page/project/setting/webhook/WebHooksPage" },
  { suffix: "/~settings/ai", page: "ProjectAiSettingPage", title: "AI Settings", ref: "web/page/project/setting/ai/ProjectAiSettingPage" },
  { suffix: "/~settings/workspace-spec", page: "WorkspaceSpecsPage", title: "Workspace Specs", ref: "web/page/project/setting/workspacespec/WorkspaceSpecsPage" },
  { suffix: "/~settings/:pluginSetting", page: "ContributedProjectSettingPage", title: "Project Settings", ref: "web/page/project/setting/pluginsettings/ContributedProjectSettingPage" },
];

/** Longest suffix first so `/~issues/new` wins over `/~issues/:issue`. */
export const PROJECT_ROUTE_SUFFIXES_SORTED = [...PROJECT_ROUTE_SUFFIXES].sort(
  (a, b) => b.suffix.length - a.suffix.length,
);
