services:
  buildx-server:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    ports:
      - "9910:9910"
      - "9911:9911"
    volumes:
      - buildx-data:/data
    environment:
      BUILDX_DEV: "true"

volumes:
  buildx-data:
