services:
  buildx-server:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    ports:
      - "6666:6666"
      - "6667:6667"
    volumes:
      - buildx-data:/data
    environment:
      BUILDX_DEV: "true"

volumes:
  buildx-data:
